"""
Credential Store — Secure .env file writer.

Security guarantees:
  - .env written with 0600 permissions (owner-only on Unix)
  - .gitignore verified to include .env
  - Full keys NEVER printed, logged, or included in exceptions
  - Future roadmap: OS keychain integration (macOS/Windows/Linux)
"""

import os
import stat
import logging
from pathlib import Path
from typing import Dict, Optional

from qwed_new.providers.key_validator import mask_key

logger = logging.getLogger(__name__)


def _find_project_root(start: Optional[Path] = None) -> Path:
    """Walk up from start dir to find the project root (has pyproject.toml or .git)."""
    current = start or Path.cwd()
    for parent in [current, *current.parents]:
        if (parent / "pyproject.toml").exists() or (parent / ".git").exists():
            return parent
    return current


def write_env_file(
    env_vars: Dict[str, str],
    project_root: Optional[Path] = None,
    active_provider: Optional[str] = None,
) -> Path:
    """
    Write or update .env file with provider credentials.

    Args:
        env_vars: Dict of VAR_NAME -> value to write
        project_root: Project root directory (auto-detected if None)
        active_provider: Provider slug to set as ACTIVE_PROVIDER

    Returns:
        Path to the written .env file
    """
    root = project_root or _find_project_root()
    env_path = root / ".env"

    # Read existing .env content (preserve other vars)
    existing_vars: Dict[str, str] = {}
    if env_path.exists():
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    existing_vars[key.strip()] = value.strip()

    # Merge: new vars override existing
    merged = {**existing_vars, **env_vars}
    if active_provider:
        merged["ACTIVE_PROVIDER"] = active_provider

    # Write .env
    lines = [
        "# QWED Environment Configuration",
        "# Generated by: qwed init",
        "# WARNING: Contains secrets. NEVER commit this file.",
        "",
    ]

    if "ACTIVE_PROVIDER" in merged:
        lines.append(f"# Active LLM Provider")
        lines.append(f"ACTIVE_PROVIDER={merged.pop('ACTIVE_PROVIDER')}")
        lines.append("")

    for key, value in sorted(merged.items()):
        lines.append(f"{key}={value}")

    lines.append("")  # trailing newline

    with open(env_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    # Set restrictive permissions (0600 on Unix, best-effort on Windows)
    try:
        if os.name != "nt":
            os.chmod(env_path, stat.S_IRUSR | stat.S_IWUSR)  # 0600
            logger.info(f".env written with 0600 permissions: {env_path}")
        else:
            # Windows: remove group/other read via icacls (best effort)
            logger.info(f".env written: {env_path} (Windows — set permissions manually)")
    except OSError as e:
        logger.warning(f"Could not set .env permissions: {e}")

    return env_path


def verify_gitignore(project_root: Optional[Path] = None) -> bool:
    """
    Check that .gitignore includes .env.

    Returns True if .env is properly gitignored.
    """
    root = project_root or _find_project_root()
    gitignore_path = root / ".gitignore"

    if not gitignore_path.exists():
        return False

    with open(gitignore_path, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if stripped == ".env" or stripped == "*.env":
                return True

    return False


def add_env_to_gitignore(project_root: Optional[Path] = None) -> bool:
    """Add .env to .gitignore if not already present."""
    root = project_root or _find_project_root()
    gitignore_path = root / ".gitignore"

    if verify_gitignore(root):
        return True  # Already there

    try:
        with open(gitignore_path, "a", encoding="utf-8") as f:
            f.write("\n# Environment variables (contains secrets)\n.env\n")
        return True
    except OSError as e:
        logger.error(f"Could not update .gitignore: {e}")
        return False
